CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(255) UNIQUE NOT NULL,
	password_hash VARCHAR(255) UNIQUE NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE stocks (
	stockid SERIAL PRIMARY KEY,
	symbol VARCHAR(10) NOT NULL,
	companyname VARCHAR(100),
	sector VARCHAR(50),
	marketcap NUMERIC(15,2),
	currentprice NUMERIC(10,2),
	dayhigh NUMERIC(10,2),
	daylow NUMERIC(10,2),
	updatedat TIMESTAMP WITHOUT TIMEZONE DEFAULT CURRENT_TIMESPAMP
);

CREATE TABLE watchlist (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	stock_id INTEGER NOT NULL REFERENCES stocks(stockid) ON DELETE CASCADE,
	createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE alerts (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	stock_id INTEGER NOT NULL REFERENCES stocks(stockid) ON DELETE CASCADE,
	target_price NUMERIC(10,2) NOT NULL,
	direction VARCHAR(4) CHECK (direction IN ('up', 'down')),
	troggered BOOLEAN DEFAULT FALSE,
	createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);